In [25]:
from PIL import ImageGrab
import numpy as np
import cv2
from win32api import GetSystemMetrics

In [26]:
width, height = GetSystemMetrics(0), GetSystemMetrics(1)

file_name = f'abc.mp4'
fourc = cv2.VideoWriter_fourcc('m', 'p', '4', 'v')
capture_video = cv2.VideoWriter(file_name, fourc, 20, (width, height))

while True:
    img = ImageGrab.grab(bbox=(0,0, width, height))
    img_np = np.array(img)
    img_np = cv2.cvtColor(img_np, cv2.COLOR_BGR2RGB)
    capture_video.write(img_np)
    cv2.imshow('screen', img_np) 
    if cv2.waitKey(10) == ord('q'):
        cv2.destroyAllWindows()
        break
    

This is Second[[[ 59  59  59]
  [ 72  73  73]
  [102 105 109]
  ...
  [157 158 146]
  [156 157 145]
  [156 157 144]]

 [[ 66  64  63]
  [ 54  54  54]
  [ 52  55  56]
  ...
  [156 158 145]
  [156 157 145]
  [155 156 144]]

 [[ 66  64  60]
  [100  99  95]
  [ 65  66  64]
  ...
  [ 18  18 109]
  [ 18  18 109]
  [ 18  18 109]]

 ...

 [[ 56  83  78]
  [ 53  80  75]
  [ 39  22   1]
  ...
  [ 14  14  14]
  [ 15  15  15]
  [ 11  11  11]]

 [[ 47  79  74]
  [ 48  81  75]
  [ 39  22   1]
  ...
  [  8   8   8]
  [  8   8   8]
  [  9   9   9]]

 [[ 50  87  79]
  [ 50  87  78]
  [ 39  22   1]
  ...
  [ 10  10  10]
  [ 10  10  10]
  [ 10  10  10]]]
